"""baseline: the schema as it stands

Revision ID: 901136a37e2b
Revises: 
Create Date: 2026-09-23 13:06:31.634480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '901136a37e2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('github_login', sa.String(length=100), nullable=True),
    sa.Column('role_title', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_archived_at'), ['archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_github_login'), ['github_login'], unique=True)

    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule', sa.String(length=40), nullable=False),
    sa.Column('fingerprint', sa.String(length=300), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('current_value', sa.String(length=255), nullable=True),
    sa.Column('proposed_value', sa.String(length=255), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint', name='uq_suggestion_fingerprint')
    )
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggestions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_rule'), ['rule'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_status'), ['status'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('definition_of_done', sa.Text(), nullable=True),
    sa.Column('stakeholder', sa.String(length=255), nullable=True),
    sa.Column('tech_stack', sa.String(length=255), nullable=True),
    sa.Column('repo', sa.String(length=255), nullable=True),
    sa.Column('local_path', sa.String(length=1024), nullable=True),
    sa.Column('protected_paths', sa.Text(), nullable=True),
    sa.Column('test_command', sa.String(length=500), nullable=True),
    sa.Column('test_dir', sa.String(length=500), nullable=True),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.Column('workspace', sa.String(length=20), nullable=False),
    sa.Column('progress_override', sa.Integer(), nullable=True),
    sa.Column('retro', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['leader_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_archived_at'), ['archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_leader_id'), ['leader_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_repo'), ['repo'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_workspace'), ['workspace'], unique=False)

    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=True),
    sa.Column('feature', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('web_searches', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.Column('seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_feature'), ['feature'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_ok'), ['ok'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_project_id'), ['project_id'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_project_id'), ['project_id'], unique=False)

    op.create_table('brainstorms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brainstorms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brainstorms_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_brainstorms_project_id'), ['project_id'], unique=False)

    op.create_table('code_explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('content_sha', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'path', 'start_line', 'end_line', 'content_sha', name='uq_explanation_selection')
    )
    with op.batch_alter_table('code_explanations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_explanations_content_sha'), ['content_sha'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_explanations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_explanations_project_id'), ['project_id'], unique=False)

    op.create_table('dashboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('workspace_id', sa.String(length=255), nullable=True),
    sa.Column('workspace_name', sa.String(length=255), nullable=True),
    sa.Column('dataset_id', sa.String(length=255), nullable=True),
    sa.Column('dataset_name', sa.String(length=255), nullable=True),
    sa.Column('last_refresh_at', sa.DateTime(), nullable=True),
    sa.Column('refresh_status', sa.String(length=40), nullable=True),
    sa.Column('refresh_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboards_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dashboards_refresh_status'), ['refresh_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_dashboards_source'), ['source'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('author_login', sa.String(length=100), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_author_login'), ['author_login'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_status'), ['status'], unique=False)

    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_links_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_links_project_id'), ['project_id'], unique=False)

    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestones_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_status'), ['status'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_source'), ['source'], unique=False)

    op.create_table('project_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'person_id', name='uq_member_project_person')
    )
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_members_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_members_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_members_role'), ['role'], unique=False)

    op.create_table('brainstorm_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brainstorm_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brainstorm_id'], ['brainstorms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brainstorm_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brainstorm_messages_brainstorm_id'), ['brainstorm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brainstorm_messages_created_at'), ['created_at'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('estimate_hours', sa.Float(), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_milestone_id'), ['milestone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_parent_task_id'), ['parent_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    op.create_table('activity_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('linked_by', sa.String(length=20), nullable=True),
    sa.Column('file_stats', sa.Text(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_events_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_repo'), ['repo'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_task_id'), ['task_id'], unique=False)

    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_required', sa.Boolean(), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('auto_apply', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tests_passed', sa.Boolean(), nullable=True),
    sa.Column('test_output', sa.Text(), nullable=True),
    sa.Column('changes_json', sa.Text(), nullable=True),
    sa.Column('diff', sa.Text(), nullable=True),
    sa.Column('base_sha', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_task_id'), ['task_id'], unique=False)

    op.create_table('time_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_logs_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_logs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_logs_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_logs_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_logs_work_date'), ['work_date'], unique=False)

    op.create_table('code_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('before_text', sa.Text(), nullable=True),
    sa.Column('after_text', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('reverted_at', sa.DateTime(), nullable=True),
    sa.Column('base_sha', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['approved_by_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('code_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_changes_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_changes_approved_at'), ['approved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_changes_approved_by_id'), ['approved_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_changes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_changes_origin'), ['origin'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_changes_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_changes_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_changes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_changes_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_changes_task_id'))
        batch_op.drop_index(batch_op.f('ix_code_changes_status'))
        batch_op.drop_index(batch_op.f('ix_code_changes_project_id'))
        batch_op.drop_index(batch_op.f('ix_code_changes_path'))
        batch_op.drop_index(batch_op.f('ix_code_changes_origin'))
        batch_op.drop_index(batch_op.f('ix_code_changes_created_at'))
        batch_op.drop_index(batch_op.f('ix_code_changes_approved_by_id'))
        batch_op.drop_index(batch_op.f('ix_code_changes_approved_at'))
        batch_op.drop_index(batch_op.f('ix_code_changes_agent_run_id'))

    op.drop_table('code_changes')
    with op.batch_alter_table('time_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_logs_work_date'))
        batch_op.drop_index(batch_op.f('ix_time_logs_task_id'))
        batch_op.drop_index(batch_op.f('ix_time_logs_source'))
        batch_op.drop_index(batch_op.f('ix_time_logs_project_id'))
        batch_op.drop_index(batch_op.f('ix_time_logs_category'))

    op.drop_table('time_logs')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_task_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_status'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_created_at'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_events_task_id'))
        batch_op.drop_index(batch_op.f('ix_activity_events_repo'))
        batch_op.drop_index(batch_op.f('ix_activity_events_provider'))
        batch_op.drop_index(batch_op.f('ix_activity_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_activity_events_person_id'))
        batch_op.drop_index(batch_op.f('ix_activity_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_activity_events_kind'))

    op.drop_table('activity_events')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_source'))
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_priority'))
        batch_op.drop_index(batch_op.f('ix_tasks_parent_task_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_milestone_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_due_date'))

    op.drop_table('tasks')
    with op.batch_alter_table('brainstorm_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brainstorm_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_brainstorm_messages_brainstorm_id'))

    op.drop_table('brainstorm_messages')
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_members_role'))
        batch_op.drop_index(batch_op.f('ix_project_members_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_members_person_id'))

    op.drop_table('project_members')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_source'))
        batch_op.drop_index(batch_op.f('ix_notes_project_id'))
        batch_op.drop_index(batch_op.f('ix_notes_kind'))
        batch_op.drop_index(batch_op.f('ix_notes_created_at'))

    op.drop_table('notes')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestones_status'))
        batch_op.drop_index(batch_op.f('ix_milestones_project_id'))
        batch_op.drop_index(batch_op.f('ix_milestones_due_date'))

    op.drop_table('milestones')
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_links_project_id'))
        batch_op.drop_index(batch_op.f('ix_links_kind'))

    op.drop_table('links')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_status'))
        batch_op.drop_index(batch_op.f('ix_feedback_source'))
        batch_op.drop_index(batch_op.f('ix_feedback_project_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_person_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_feedback_author_login'))

    op.drop_table('feedback')
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboards_source'))
        batch_op.drop_index(batch_op.f('ix_dashboards_refresh_status'))
        batch_op.drop_index(batch_op.f('ix_dashboards_project_id'))

    op.drop_table('dashboards')
    with op.batch_alter_table('code_explanations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_explanations_project_id'))
        batch_op.drop_index(batch_op.f('ix_code_explanations_created_at'))
        batch_op.drop_index(batch_op.f('ix_code_explanations_content_sha'))

    op.drop_table('code_explanations')
    with op.batch_alter_table('brainstorms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brainstorms_project_id'))
        batch_op.drop_index(batch_op.f('ix_brainstorms_created_at'))

    op.drop_table('brainstorms')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_project_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_project_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_ok'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_model'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_feature'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_at'))

    op.drop_table('ai_usage')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_workspace'))
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_repo'))
        batch_op.drop_index(batch_op.f('ix_projects_priority'))
        batch_op.drop_index(batch_op.f('ix_projects_leader_id'))
        batch_op.drop_index(batch_op.f('ix_projects_category'))
        batch_op.drop_index(batch_op.f('ix_projects_archived_at'))

    op.drop_table('projects')
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestions_status'))
        batch_op.drop_index(batch_op.f('ix_suggestions_rule'))
        batch_op.drop_index(batch_op.f('ix_suggestions_created_at'))

    op.drop_table('suggestions')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_github_login'))
        batch_op.drop_index(batch_op.f('ix_people_archived_at'))

    op.drop_table('people')
    # ### end Alembic commands ###
