"""close the drift ensure_columns could not reach

Revision ID: c567d38836cb
Revises: 901136a37e2b
Create Date: 2026-09-23 12:57:16.538643

Before migrations, this schema was maintained by `create_all` plus an
additive-only `ensure_columns`. That combination can add a column and
nothing else, so every index, foreign key and NOT NULL added to a model
after its table first existed was never applied to a database that already
had that table. On the database this was written against: 8 missing
indexes, 3 missing foreign keys, and 4 columns still nullable that the
models had required for months.

**This migration is conditional, and that is deliberate.** The baseline
before it was autogenerated from the models, so a database built from the
migrations alone already has everything here; a database that predates them
has some of it, depending on when each table was first created. Neither
"always create" nor "never create" is right for both, so each item is
applied only if it is actually missing. The alternative -- a baseline
describing a schema nobody can reconstruct, hand-written across 19 tables
-- would be guesswork presented as history.

Foreign keys are deferred while this runs; see `alembic/env.py` for why.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "c567d38836cb"
down_revision: Union[str, Sequence[str], None] = "901136a37e2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# (table, column) pairs the models require and an older database may not.
NOT_NULL = [
    ("notes", "source", sa.String(length=10), "'human'"),
    ("tasks", "source", sa.String(length=10), "'human'"),
    ("time_logs", "source", sa.String(length=10), "'human'"),
    ("projects", "workspace", sa.String(length=20), "'work'"),
]

# (table, index name, columns)
INDEXES = [
    ("activity_events", "ix_activity_events_person_id", ["person_id"]),
    ("code_changes", "ix_code_changes_task_id", ["task_id"]),
    ("notes", "ix_notes_source", ["source"]),
    ("projects", "ix_projects_leader_id", ["leader_id"]),
    ("projects", "ix_projects_repo", ["repo"]),
    ("projects", "ix_projects_workspace", ["workspace"]),
    ("tasks", "ix_tasks_source", ["source"]),
    ("time_logs", "ix_time_logs_source", ["source"]),
]

# (table, constraint name, referred table, local columns, remote columns)
FOREIGN_KEYS = [
    (
        "activity_events",
        "fk_activity_events_person_id_people",
        "people",
        ["person_id"],
        ["id"],
    ),
    ("code_changes", "fk_code_changes_task_id_tasks", "tasks", ["task_id"], ["id"]),
    ("projects", "fk_projects_leader_id_people", "people", ["leader_id"], ["id"]),
]


def existing_indexes(inspector, table):
    return {index["name"] for index in inspector.get_indexes(table)}


def referred_tables(inspector, table):
    """Which tables this one already points at, named or not.

    The question `upgrade` asks. SQLite's own foreign keys carry no name
    unless someone gave them one, so "is there already a key to `people`"
    is the only form of the question that works on both a database built
    from the baseline and one that predates it.
    """
    return {key["referred_table"] for key in inspector.get_foreign_keys(table)}


def named_constraints(inspector, table):
    """Only the foreign keys that carry a name.

    The question `downgrade` asks, and a different one. A key created by
    the baseline's `create_table` is anonymous, and a database that came
    that way should keep it: walking back to the baseline means arriving at
    the baseline, not at something missing a constraint it always had.
    """
    return {
        key["name"] for key in inspector.get_foreign_keys(table) if key.get("name")
    }


def nullable(inspector, table, column):
    for found in inspector.get_columns(table):
        if found["name"] == column:
            return found["nullable"]
    return None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())

    # Backfill before tightening. A NOT NULL against a column holding nulls
    # fails halfway through a table rebuild, which is a worse place to stop
    # than before starting.
    for table, column, _type, default in NOT_NULL:
        if table not in tables or nullable(inspector, table, column) is not True:
            continue
        op.execute(
            sa.text(
                f"UPDATE {table} SET {column} = {default} WHERE {column} IS NULL"
            )
        )

    for table in sorted(tables):
        wanted_indexes = [
            (name, columns) for t, name, columns in INDEXES if t == table
        ]
        wanted_keys = [
            (name, target, local, remote)
            for t, name, target, local, remote in FOREIGN_KEYS
            if t == table
        ]
        wanted_null = [
            (column, type_)
            for t, column, type_, _default in NOT_NULL
            if t == table and nullable(inspector, t, column) is True
        ]
        have_indexes = existing_indexes(inspector, table)
        have_targets = referred_tables(inspector, table)

        missing_indexes = [
            (name, columns) for name, columns in wanted_indexes if name not in have_indexes
        ]
        missing_keys = [key for key in wanted_keys if key[1] not in have_targets]

        # NOT NULL and foreign keys need batch mode, because SQLite can only
        # change them by rebuilding the table. Indexes do not -- `CREATE
        # INDEX` works directly -- and putting them in the same batch block
        # makes them fight the rebuild, which recreates the table's indexes
        # itself.
        if wanted_null or missing_keys:
            with op.batch_alter_table(table, schema=None) as batch_op:
                for column, type_ in wanted_null:
                    batch_op.alter_column(column, existing_type=type_, nullable=False)
                for name, target, local, remote in missing_keys:
                    batch_op.create_foreign_key(name, target, local, remote)

        # Re-read: the rebuild above may have carried indexes across or not,
        # depending on how the table was originally defined.
        have_indexes = existing_indexes(sa.inspect(bind), table)
        for name, columns in missing_indexes:
            if name not in have_indexes:
                op.create_index(name, table, columns, unique=False)


def downgrade() -> None:
    """Remove the foreign keys this added, and leave the rest.

    Deliberately partial, and worth being precise about why.

    The revision below this one -- the baseline -- was autogenerated from
    the models, so it *already contains* these indexes and NOT NULL
    constraints. A database that reached this revision through the baseline
    has them from there; a database that predates migrations got them from
    here. Nothing in the schema records which, because an index carries no
    provenance.

    Given that, dropping them on the way back is the worse guess: on a
    baseline-built database it would remove constraints that revision
    requires, leaving it describing a schema that never existed. Leaving
    them means a pre-Alembic database walking back keeps a few indexes it
    did not start with, which is a superset and harms nothing.

    The foreign keys are different, and are undone, because this migration
    names the ones it creates and the baseline's are anonymous -- so here
    the provenance *is* recorded, and the precise thing is possible.
    """
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    for table in sorted(set(inspector.get_table_names()), reverse=True):
        mine = [
            name for t, name, _target, _l, _r in FOREIGN_KEYS
            if t == table and name in named_constraints(inspector, table)
        ]
        if not mine:
            continue
        with op.batch_alter_table(table, schema=None) as batch_op:
            for name in mine:
                batch_op.drop_constraint(name, type_="foreignkey")
